### PR TITLE
Add support for the 'dnf' package manager

### PR DESCRIPTION
**Pull request by FreedomBen**
Tested on Fedora 22

### CODE REVIEW

**Comment by FreedomBen** [comment]
Is that a legitimate failure?

**Comment by FreedomBen** [comment]
Does anybody watch this repo?

**Comment by havenwood** [comment]
The failing OS X test is unrelated and fixed with 683129899218ca91b43fcf74a565a86006e1917d.

**Comment by postmodern** [comment]
:+1: dnf has now replaced yum.

**Pull request merged**
