### PR TITLE
Clarify ruby installation instructions for newer Ruby releases not listed by ruby-install

### PR DESCRIPTION
**Pull request by josh-nz**
I've attempted to improve the documentation and language around installing newer Rubies that are not know by ruby-install. This is in commit c6fd8c4.

I've also adjusted the output when ruby-install lists known Rubies to be a little more clearer. This is in commit 7356c6a.

Now 7356c6a will mean a new release to be of benefit to users, and there may not be another release before the `--update` option in #175 is included, so you may wish to exclude this commit. I've also not run the tests on this change as I was unsure how to do so and what changes they'd leave on my system regarding file download tests. I have however looked at the `supported_rubies_test.sh` tests and can't see any issues. My changes are just textual.

This is my first pull request, so unsure exactly how everything works. I believe you can cherry pick just the documentation changes, but if you can't and require two separate pull requests just let me know and I'll create them.

### CODE REVIEW

**Comment by sbeam** [comment]
thanks for this, it helped me figure out the solution to not being able to extract ruby 2.2.0 - which by the way, the output of trying and failing to checksum an unlisted ruby is quite cryptic, and seems like a bug where it fails to extract the archive:

```
$ ruby-install ruby 2.2
>>> Installing ruby 2.2 into /Users/samoeba/.rubies/ruby-2.2 ...
>>> Installing dependencies for ruby 2.2 ...
Warning: openssl-1.0.2 already installed
Warning: readline-6.3.8 already installed
Warning: libyaml-0.1.6_1 already installed
Warning: gdbm-1.11 already installed
Warning: libffi-3.0.13 already installed
>>> Downloading http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.tar.bz2 into /Users/samoeba/src ...
>>> Verifying ruby-2.2.tar.bz2 ...
*** No md5 checksum for /Users/samoeba/src/ruby-2.2.tar.bz2
*** No sha1 checksum for /Users/samoeba/src/ruby-2.2.tar.bz2
*** No sha256 checksum for /Users/samoeba/src/ruby-2.2.tar.bz2
*** No sha512 checksum for /Users/samoeba/src/ruby-2.2.tar.bz2
>>> Extracting ruby-2.2.tar.bz2 to /Users/samoeba/src/ruby-2.2 ...
/usr/local/bin/ruby-install: line 40: cd: /Users/samoeba/src/ruby-2.2: No such file or directory
>>> Regenerating ./configure script ...
autoreconf: 'configure.ac' or 'configure.in' is required
!!! Configuration of ruby 2.2 failed!
```

**Comment by postmodern** [comment]
Care to revisit this PR now that `--latest` is available? I tried to ensure the wording was clear by using "latest version" vs. "current stable version".

**Comment by josh-nz** [comment]
Hi, I've since moved on from Ruby and have a new rebuilt laptop. Consequently I no longer have ruby-install and currently see no requirement for it. For me to revisit this I'm going to have understand the changes you have made and how it impacts things, which I don't have time for at present.

**Comment by postmodern** [comment]
The summary of the changes are listed in the [ChangeLog](https://github.com/postmodern/ruby-install/blob/master/ChangeLog.md#060--2015-12-25). If you don't have time I'll go ahead and close this.

**Pull request closed without merging**
