### PR TITLE
should be 2.3.0 instead of 2.3

### PR DESCRIPTION
**Pull request by zjlovezj**

### CODE REVIEW

**Comment by havenwood** [comment]
But `ruby-install ruby 2.3` will install the latest TEENY version which won't stay 0. The next example shows a full version.

**Comment by zjlovezj** [comment]
Well, it might be a bug then.
I got below error response.

➜  ~  ruby-install ruby 2.3
>>> Installing ruby 2.3 into /Users/michael/.rubies/ruby-2.3 ...
>>> Installing dependencies for ruby 2.3 ...
Warning: openssl-1.0.2e already installed
Warning: readline-6.3.8 already installed
Warning: libyaml-0.1.6_1 already installed
Warning: gdbm-1.11 already installed
Warning: libffi-3.0.13 already installed
>>> Downloading http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.tar.bz2 into /Users/michael/src ...
--2015-12-27 00:40:37--  http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.tar.bz2
Resolving cache.ruby-lang.org... 103.245.222.233
Connecting to cache.ruby-lang.org|103.245.222.233|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-27 00:40:38 ERROR 404: Not Found.

!!! Download of http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.tar.bz2 failed!

**Comment by havenwood** [comment]
Hem, it seems you don't yet have the latest versions sync. Could you try?:
```sh
ruby-install --latest ruby 2.3
```

**Comment by zjlovezj** [comment]
You are right.
I use homebrew to install ruby-install today.
It's 0.5.0.
I think this PR can be closed.
Thanks.

**Pull request closed without merging**
