### PR TITLE
Fix macos handling for truffleruby artifacts

### PR DESCRIPTION
**Pull request by rwstauner**
We change darwin to macos at the top of this file.

I confirmed that on my mac i can install
- truffleruby-23.0.0
- truffleruby-22.3.0
- truffleruby-graalvm-23.0.0
- truffleruby-graalvm-22.3.0

### CODE REVIEW

**Review by postmodern — APPROVED** [review]

**Comment by postmodern** [comment]
@eregon any other testing or fixes, or should I start preparing a 0.9.1 release?

**Comment by nirvdrum** [comment]
@postmodern I think we're all set now. It was an unfortunate copy & paste issue. @rwstauner has verified the macOS builds install correctly and @eregon had confirmed the Linux ones do as well. Whenever GitHub adds support for macOS ARM machines we may do well to add automated tests that check the tarball downloads work.

**Comment by eregon** [comment]
Yes, all good, a release would be great :)

**Comment by postmodern** [comment]
Will try to do that tomorrow, after the dentist appointment...

**Pull request merged**
