### PR TITLE
Do not use sudo for brew if not necessary

### PR DESCRIPTION
**Pull request by rb83**
Normally, brew installations do not require sudo. There might be
certain cases where it does, so this commit preserves the old behaviour
where ownership of the brew script isn't the same as the user executing
ruby-install. Otherwise, sudo is omitted.

This also solves #128 for situations where the issue was caused by sudo
not preserving the user's environment (proxy failures could also be
caused by a host of other reasons, but it's the main reason why the issue was created originally).

### CODE REVIEW

**Comment by rb83** [comment]
CI failures seem to have been caused in unrelated files?

**Comment by rb83** [comment]
rebased on upstream master in order to have the checks re-run.

**Comment by rb83** [comment]
Also solves #376.

**Comment by postmodern** [comment]
0.8.2 has been tagged. Now to wait for homebrew to pull in the new formula.

**Pull request merged**
