### PR TITLE
Fail truffleruby installation if install_dir is /usr/local

### PR DESCRIPTION
**Pull request by missingcharacter**
Trying to close https://github.com/postmodern/ruby-install/issues/398

### CODE REVIEW

**Review by eregon — APPROVED** [review]
Looks good to me.

I guess technically one could use other system-wide locations (e.g., /usr), but probably nobody does in practice?

**Comment by postmodern** [comment]
Thoughts on moving the `fail` into the `install_ruby` function, at the top?

**Comment by missingcharacter** [comment]
@postmodern like this (see new commit) or turn it into an `if`?

**Comment by postmodern** [comment]
@missingcharacter yeah `if` would be better since we're only doing one comparison.

Also, since we're in the `install_ruby` function, we could also use `error` and `return 1` to abort back to [bin/ruby-install](https://github.com/postmodern/ruby-install/blob/257746199f83794294326383d4a3ac8f37ab9d4a/bin/ruby-install#L50) where a generic error message would also be printed. You're call on whether to print one error message and immediately exit, or print two error messages.

**Comment by missingcharacter** [comment]
@postmodern how about now?

**Comment by postmodern** [comment]
Squash merged, even though GitHub Actions keeps failing shunit2 test suites only on macOS; still need to investigate that.

**Pull request merged**
