### PR TITLE
Update stable.txt

### PR DESCRIPTION
**Pull request by joelparkerhenderson**

### CODE REVIEW

**Comment by postmodern** [comment]
We're actually in the process of moving towards downloading/updating from [ruby-versions](https://github.com/postmodern/ruby-versions). See the [ruby-versions](https://github.com/postmodern/ruby-install/tree/ruby-versions) branch for WIP.

**Comment by SixArm** [comment]
What do you want people using right now, in production, to get current Ruby? (I'm the OP)

**Comment by postmodern** [comment]
@SixArm I will try to release 0.5.0 around New Years. Just needs more tests and feedback.

As for install ruby in production, PLEASE use a packaged ruby, such as [BrightBox's ruby-ng](https://github.com/postmodern/ruby-install/pull/248#issuecomment-167028102) packages for Ubuntu.

**Comment by postmodern** [comment]
correction, I meant ruby-install 0.6.0... Do checkout the [ruby-versions](https://github.com/postmodern/ruby-install/tree/ruby-versions) branch though. I'm looking for feedback on the download-on-first-run feature and `--update` option.

**Comment by joelparkerhenderson** [comment]
Thanks. I use ruby-install along with BrightBox to run multiple ruby versions, e.g. the system ruby is BrightBox, and custom ruby versions are e.g. /opt/ruby/x.z.y and /opt/jruby/x.y.z. I'll try the ruby-versions branch now and let you know how it goes.

**Comment by joelparkerhenderson** [comment]
Here's what I get when I try:

    $ git checkout ruby-versions
    Branch ruby-versions set up to track remote branch ruby-versions from origin.
    Switched to a new branch 'ruby-versions'
    $ git pull
    Already up-to-date.
    $ make clean
    rm -f pkg/ruby-install-0.6.0.tar.gz pkg/ruby-install-0.6.0.asc
    $ make
    make: `pkg' is up to date.
    $ make install
    for dir in `find bin share -type d`; do mkdir -p /usr/local/$dir; done
    for file in `find bin share -type f`; do cp $file /usr/local/$file; done
    mkdir -p /usr/local/share/doc/ruby-install-0.6.0
    cp -r *.md *.txt /usr/local/share/doc/ruby-install-0.6.0/
    $ ruby-install --version
    ruby-install: 0.6.0
    $ ruby-install
    Stable ruby versions:
      ruby:
    cat: /var/root/.cache/ruby-install/ruby/stable.txt: No such file or directory
      jruby:
    cat: /var/root/.cache/ruby-install/jruby/stable.txt: No such file or directory
      rbx:
    cat: /var/root/.cache/ruby-install/rbx/stable.txt: No such file or directory
      maglev:
   cat: /var/root/.cache/ruby-install/maglev/stable.txt: No such file or directory
      mruby:
   cat: /var/root/.cache/ruby-install/mruby/stable.txt: No such file or directory

**Comment by postmodern** [comment]
@joelparkerhenderson thanks. You caught a rather dumb typo of mine. Still need to add more tests...

**Pull request closed without merging**
