### PR TITLE
Updated versions/checksums

### PR DESCRIPTION
**Pull request by Mic92**
related to #202

### CODE REVIEW

**Comment by aprescott** [comment]
@Mic92 like https://github.com/postmodern/ruby-install/pull/202#issuecomment-73633614 says, I think you want to PR both this and #202 against https://github.com/postmodern/ruby-versions, not this repo.

**Comment by Mic92** [comment]
@aprescott the questions is who pulls at which time from ruby-versions to ruby-install? I used the script to update the checksums...

**Comment by aprescott** [comment]
@Mic92 I don't know but the [repository contribution guidelines](https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/CONTRIBUTING.md#versionschecksums) say to not create PRs like this. I assume the maintainers are responsible for pulling in `ruby-versions`, not contributors.

**Comment by aprescott** [comment]
I suspect https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/CONTRIBUTING.md#pull-request-guidelines should probably be removed? @postmodern?

**Comment by aprescott** [comment]
> be removed

I guess amended, since some of them aren't specific to versions/checksums.

**Comment by postmodern** [comment]
The [Makefile](https://github.com/postmodern/ruby-install/blob/5ea868bec37bd1d70ca84623d0f94dafd9ceed14/Makefile#L32-L36) automatically updates the versions/checksums during the release process.

**Comment by postmodern** [comment]
Updated `CONTRIBUTING` in be38c0b993709bf3c7384ed17b311923d82d48d3.

**Pull request closed without merging**
