### PR TITLE
Added proxy support

### PR DESCRIPTION
**Pull request by epinault**
proxy support #128

Let me know if I need to make some correction. Giving it a try

### CODE REVIEW

**Comment by epinault** [comment]
I see failures but they don t seem to relate to my code. Anyway to add this pull request?

**Comment by epinault** [comment]
So I see now there are check failed (which were not setup previously when I did the pull request. ) What can I do to have this pull request merge ? Or was this feature already fix in master?

**Comment by epinault** [comment]
Sorry for being persistent but I would love to get this merged if possible? OR getting some guidance on what I am missing?

**Comment by havenwood** [comment]
Hi! I know it's been a while, but thanks for the PR! It'd be nice to add an option parsing test in `test/ruby-install-tests/parse_options_test.sh` and mention the option in the manpage `doc/man/ruby-install.1.md`.

**Comment by epinault** [comment]
ok, I ll try to take a look at it

**Pull request closed without merging**
